### ISSUE TITLE
LVM ausbauen, und Partition + Ext4

### ISSUE THREAD

**Issue by quotengrote** [quotengrote/dp_schulserver#96]
Problemlösung:

wir lassen LVM weg und bauen das ganze Klassisch mit Partition + FS auf.
Wenn keine Gegenvorschläge kommen, setze ich das morgen um.

**Comment by quotengrote** [comment]
- [ ] Umbau vor Ort
- [ ] Doku Bereitstellung anpassen
- [ ] Rolle LVM weg
- [ ] Storage in ProxMox vor Ort anpassen
- [ ] Scripte anpassen Speicherort

**Comment by MaxGoe** [comment]
@quotengrote klinkt soweit gut nun nun die Frage wieso wollten wir überhaupt einen LVM benutzen im Vergleich zu Partitionen mit FS

**Comment by quotengrote** [comment]
Weil wir damit prinzipiell dynamisch vergrößern und verkleinern, Platten anhängen usw. können. Aber reines vergrößern geht auch mit der Lösung, nur halt nicht über mehrere Volumes.

**Comment by quotengrote** [comment]
erledigt
